### ISSUE TITLE
A question about 'produce_txt.py'

### ISSUE THREAD

**Issue by fandouble** [XuhuiZhou/CDA#3]
with open(data_path) as csv_file:
    reader = csv.reader(csv_file, quotechar='"')
    for idx, line in enumerate(reader):
        text_1 = ""
        text_2 = "" #**"text_1"and "text_2" are empty,right?**
        line[1] = line[1].replace('\001', '')
        line[2] = line[2].replace('\001', '')
        label = int(line[0])
        text_1 = process(text_1)#**'process(text_1)' ?Should there be process(line[1])**
        text_2 = process(text_2)#**'process(text_2)' ?Should there be process(line[2])**
        idx_1 = len(text_1)
        idx_2 = len(text_2)
        g.write('{}\n'.format(idx_1))
        g.write('{}\n'.format(idx_2))
        for i in text_1:
            f.write(i+'\n')
        for i in text_2:
            f.write(i+'\n')

**Comment by XuhuiZhou** [comment]
Hi, thanks for pointing that out. I think you are right. The process function should take in an `str`.
